function TermaiMoji() {
  const emojiMap = {};

  return {
    register(emoji, { src }) {
      emojiMap[emoji] = src;
    },
    
    init(base = "https://raw.githubusercontent.com/Rifza123/termai-moji/refs/heads/main/emojis/ios/"){
      this.register("\ud83d\udc4d", {src: base +"+1.png"});
      this.register("\ud83d\udc4e", {src: base +"-1.png"});
      this.register("\ud83d\udcaf", {src: base +"100.png"});
      this.register("\ud83d\udd22", {src: base +"1234.png"});
      this.register("\ud83c\udfb1", {src: base +"8ball.png"});
      this.register("\ud83c\udd70", {src: base +"a.png"});
      this.register("\ud83c\udd8e", {src: base +"ab.png"});
      this.register("\ud83d\udd24", {src: base +"abc.png"});
      this.register("\ud83d\udd21", {src: base +"abcd.png"});
      this.register("\ud83c\ude51", {src: base +"accept.png"});
      this.register("\ud83d\udea1", {src: base +"aerial_tramway.png"});
      this.register("✈", {src: base +"airplane.png"});
      this.register("✈️", {src: base +"airplane.png"});
      this.register("⏰", {src: base +"alarm_clock.png"});
      this.register("\ud83d\udc7d", {src: base +"alien.png"});
      this.register("\ud83d\ude91", {src: base +"ambulance.png"});
      this.register("⚓", {src: base +"anchor.png"});
      this.register("⚓️", {src: base +"anchor.png"});
      this.register("\ud83d\udc7c", {src: base +"angel.png"});
      this.register("\ud83d\udca2", {src: base +"anger.png"});
      this.register("\ud83d\ude20", {src: base +"angry.png"});
      this.register("\ud83d\ude27", {src: base +"anguished.png"});
      this.register("\ud83d\udc1c", {src: base +"ant.png"});
      this.register("\ud83c\udf4e", {src: base +"apple.png"});
      this.register("♒", {src: base +"aquarius.png"});
      this.register("♒️", {src: base +"aquarius.png"});
      this.register("♈", {src: base +"aries.png"});
      this.register("♈️", {src: base +"aries.png"});
      this.register("◀", {src: base +"arrow_backward.png"});
      this.register("◀️", {src: base +"arrow_backward.png"});
      this.register("⏬", {src: base +"arrow_double_down.png"});
      this.register("⏫", {src: base +"arrow_double_up.png"});
      this.register("⬇", {src: base +"arrow_down.png"});
      this.register("⬇️", {src: base +"arrow_down.png"});
      this.register("\ud83d\udd3d", {src: base +"arrow_down_small.png"});
      this.register("▶", {src: base +"arrow_forward.png"});
      this.register("▶️", {src: base +"arrow_forward.png"});
      this.register("⤵", {src: base +"arrow_heading_down.png"});
      this.register("⤵️", {src: base +"arrow_heading_down.png"});
      this.register("⤴", {src: base +"arrow_heading_up.png"});
      this.register("⤴️", {src: base +"arrow_heading_up.png"});
      this.register("⬅", {src: base +"arrow_left.png"});
      this.register("⬅️", {src: base +"arrow_left.png"});
      this.register("↙", {src: base +"arrow_lower_left.png"});
      this.register("↙️", {src: base +"arrow_lower_left.png"});
      this.register("↘", {src: base +"arrow_lower_right.png"});
      this.register("↘️", {src: base +"arrow_lower_right.png"});
      this.register("➡", {src: base +"arrow_right.png"});
      this.register("➡️", {src: base +"arrow_right.png"});
      this.register("↪", {src: base +"arrow_right_hook.png"});
      this.register("↪️", {src: base +"arrow_right_hook.png"});
      this.register("⬆", {src: base +"arrow_up.png"});
      this.register("⬆️", {src: base +"arrow_up.png"});
      this.register("↕", {src: base +"arrow_up_down.png"});
      this.register("↕️", {src: base +"arrow_up_down.png"});
      this.register("\ud83d\udd3c", {src: base +"arrow_up_small.png"});
      this.register("↖", {src: base +"arrow_upper_left.png"});
      this.register("↖️", {src: base +"arrow_upper_left.png"});
      this.register("↗", {src: base +"arrow_upper_right.png"});
      this.register("↗️", {src: base +"arrow_upper_right.png"});
      this.register("\ud83d\udd03", {src: base +"arrows_clockwise.png"});
      this.register("\ud83d\udd04", {src: base +"arrows_counterclockwise.png"});
      this.register("\ud83c\udfa8", {src: base +"art.png"});
      this.register("\ud83d\ude9b", {src: base +"articulated_lorry.png"});
      this.register("\ud83d\ude32", {src: base +"astonished.png"});
      this.register("\ud83d\udc5f", {src: base +"athletic_shoe.png"});
      this.register("\ud83c\udfe7", {src: base +"atm.png"});
      this.register("\ud83c\udd71", {src: base +"b.png"});
      this.register("\ud83d\udc76", {src: base +"baby.png"});
      this.register("\ud83c\udf7c", {src: base +"baby_bottle.png"});
      this.register("\ud83d\udc24", {src: base +"baby_chick.png"});
      this.register("\ud83d\udebc", {src: base +"baby_symbol.png"});
      this.register("\ud83d\udd19", {src: base +"back.png"});
      this.register("\ud83d\udec4", {src: base +"baggage_claim.png"});
      this.register("\ud83c\udf88", {src: base +"balloon.png"});
      this.register("☑", {src: base +"ballot_box_with_check.png"});
      this.register("☑️", {src: base +"ballot_box_with_check.png"});
      this.register("\ud83c\udf8d", {src: base +"bamboo.png"});
      this.register("\ud83c\udf4c", {src: base +"banana.png"});
      this.register("‼", {src: base +"bangbang.png"});
      this.register("‼️", {src: base +"bangbang.png"});
      this.register("\ud83c\udfe6", {src: base +"bank.png"});
      this.register("\ud83d\udcca", {src: base +"bar_chart.png"});
      this.register("\ud83d\udc88", {src: base +"barber.png"});
      this.register("⚾", {src: base +"baseball.png"});
      this.register("⚾️", {src: base +"baseball.png"});
      this.register("\ud83c\udfc0", {src: base +"basketball.png"});
      this.register("\ud83d\udec0", {src: base +"bath.png"});
      this.register("\ud83d\udec1", {src: base +"bathtub.png"});
      this.register("\ud83d\udd0b", {src: base +"battery.png"});
      this.register("\ud83d\udc3b", {src: base +"bear.png"});
      this.register("\ud83d\udc1d", {src: base +"bee.png"});
      this.register("\ud83c\udf7a", {src: base +"beer.png"});
      this.register("\ud83c\udf7b", {src: base +"beers.png"});
      this.register("\ud83d\udc1e", {src: base +"beetle.png"});
      this.register("\ud83d\udd30", {src: base +"beginner.png"});
      this.register("\ud83d\udd14", {src: base +"bell.png"});
      this.register("\ud83c\udf71", {src: base +"bento.png"});
      this.register("\ud83d\udeb4", {src: base +"bicyclist.png"});
      this.register("\ud83d\udeb2", {src: base +"bike.png"});
      this.register("\ud83d\udc59", {src: base +"bikini.png"});
      this.register("\ud83d\udc26", {src: base +"bird.png"});
      this.register("\ud83c\udf82", {src: base +"birthday.png"});
      this.register("⚫", {src: base +"black_circle.png"});
      this.register("⚫️", {src: base +"black_circle.png"});
      this.register("\ud83c\udccf", {src: base +"black_joker.png"});
      this.register("⬛", {src: base +"black_large_square.png"});
      this.register("⬛️", {src: base +"black_large_square.png"});
      this.register("◾", {src: base +"black_medium_small_square.png"});
      this.register("◾️", {src: base +"black_medium_small_square.png"});
      this.register("◼", {src: base +"black_medium_square.png"});
      this.register("◼️", {src: base +"black_medium_square.png"});
      this.register("✒", {src: base +"black_nib.png"});
      this.register("✒️", {src: base +"black_nib.png"});
      this.register("▪", {src: base +"black_small_square.png"});
      this.register("▪️", {src: base +"black_small_square.png"});
      this.register("\ud83d\udd32", {src: base +"black_square_button.png"});
      this.register("\ud83c\udf3c", {src: base +"blossom.png"});
      this.register("\ud83d\udc21", {src: base +"blowfish.png"});
      this.register("\ud83d\udcd8", {src: base +"blue_book.png"});
      this.register("\ud83d\ude99", {src: base +"blue_car.png"});
      this.register("\ud83d\udc99", {src: base +"blue_heart.png"});
      this.register("\ud83d\ude0a", {src: base +"blush.png"});
      this.register("\ud83d\udc17", {src: base +"boar.png"});
      this.register("⛵", {src: base +"boat.png"});
      this.register("⛵️", {src: base +"boat.png"});
      this.register("\ud83d\udca3", {src: base +"bomb.png"});
      this.register("\ud83d\udcd6", {src: base +"book.png"});
      this.register("\ud83d\udd16", {src: base +"bookmark.png"});
      this.register("\ud83d\udcd1", {src: base +"bookmark_tabs.png"});
      this.register("\ud83d\udcda", {src: base +"books.png"});
      this.register("\ud83d\udca5", {src: base +"boom.png"});
      this.register("\ud83d\udc62", {src: base +"boot.png"});
      this.register("\ud83d\udc90", {src: base +"bouquet.png"});
      this.register("\ud83d\ude47", {src: base +"bow.png"});
      this.register("\ud83c\udfb3", {src: base +"bowling.png"});
      this.register("\ud83d\udc66", {src: base +"boy.png"});
      this.register("\ud83c\udf5e", {src: base +"bread.png"});
      this.register("\ud83d\udc70", {src: base +"bride_with_veil.png"});
      this.register("\ud83c\udf09", {src: base +"bridge_at_night.png"});
      this.register("\ud83d\udcbc", {src: base +"briefcase.png"});
      this.register("\ud83d\udc94", {src: base +"broken_heart.png"});
      this.register("\ud83d\udc1b", {src: base +"bug.png"});
      this.register("\ud83d\udca1", {src: base +"bulb.png"});
      this.register("\ud83d\ude85", {src: base +"bullettrain_front.png"});
      this.register("\ud83d\ude84", {src: base +"bullettrain_side.png"});
      this.register("\ud83d\ude8c", {src: base +"bus.png"});
      this.register("\ud83d\ude8f", {src: base +"busstop.png"});
      this.register("\ud83d\udc64", {src: base +"bust_in_silhouette.png"});
      this.register("\ud83d\udc65", {src: base +"busts_in_silhouette.png"});
      this.register("\ud83c\udf35", {src: base +"cactus.png"});
      this.register("\ud83c\udf70", {src: base +"cake.png"});
      this.register("\ud83d\udcc6", {src: base +"calendar.png"});
      this.register("\ud83d\udcf2", {src: base +"calling.png"});
      this.register("\ud83d\udc2b", {src: base +"camel.png"});
      this.register("\ud83d\udcf7", {src: base +"camera.png"});
      this.register("♋", {src: base +"cancer.png"});
      this.register("♋️", {src: base +"cancer.png"});
      this.register("\ud83c\udf6c", {src: base +"candy.png"});
      this.register("\ud83d\udd20", {src: base +"capital_abcd.png"});
      this.register("♑", {src: base +"capricorn.png"});
      this.register("♑️", {src: base +"capricorn.png"});
      this.register("\ud83d\ude97", {src: base +"car.png"});
      this.register("\ud83d\udcc7", {src: base +"card_index.png"});
      this.register("\ud83c\udfa0", {src: base +"carousel_horse.png"});
      this.register("\ud83d\udc31", {src: base +"cat.png"});
      this.register("\ud83d\udc08", {src: base +"cat2.png"});
      this.register("\ud83d\udcbf", {src: base +"cd.png"});
      this.register("\ud83d\udcb9", {src: base +"chart.png"});
      this.register("\ud83d\udcc9", {src: base +"chart_with_downwards_trend.png"});
      this.register("\ud83d\udcc8", {src: base +"chart_with_upwards_trend.png"});
      this.register("\ud83c\udfc1", {src: base +"checkered_flag.png"});
      this.register("\ud83c\udf52", {src: base +"cherries.png"});
      this.register("\ud83c\udf38", {src: base +"cherry_blossom.png"});
      this.register("\ud83c\udf30", {src: base +"chestnut.png"});
      this.register("\ud83d\udc14", {src: base +"chicken.png"});
      this.register("\ud83d\udeb8", {src: base +"children_crossing.png"});
      this.register("\ud83c\udf6b", {src: base +"chocolate_bar.png"});
      this.register("\ud83c\udf84", {src: base +"christmas_tree.png"});
      this.register("⛪", {src: base +"church.png"});
      this.register("⛪️", {src: base +"church.png"});
      this.register("\ud83c\udfa6", {src: base +"cinema.png"});
      this.register("\ud83c\udfaa", {src: base +"circus_tent.png"});
      this.register("\ud83c\udf07", {src: base +"city_sunrise.png"});
      this.register("\ud83c\udf06", {src: base +"city_sunset.png"});
      this.register("\ud83c\udd91", {src: base +"cl.png"});
      this.register("\ud83d\udc4f", {src: base +"clap.png"});
      this.register("\ud83c\udfac", {src: base +"clapper.png"});
      this.register("\ud83d\udccb", {src: base +"clipboard.png"});
      this.register("\ud83d\udd50", {src: base +"clock1.png"});
      this.register("\ud83d\udd59", {src: base +"clock10.png"});
      this.register("\ud83d\udd65", {src: base +"clock1030.png"});
      this.register("\ud83d\udd5a", {src: base +"clock11.png"});
      this.register("\ud83d\udd66", {src: base +"clock1130.png"});
      this.register("\ud83d\udd5b", {src: base +"clock12.png"});
      this.register("\ud83d\udd67", {src: base +"clock1230.png"});
      this.register("\ud83d\udd5c", {src: base +"clock130.png"});
      this.register("\ud83d\udd51", {src: base +"clock2.png"});
      this.register("\ud83d\udd5d", {src: base +"clock230.png"});
      this.register("\ud83d\udd52", {src: base +"clock3.png"});
      this.register("\ud83d\udd5e", {src: base +"clock330.png"});
      this.register("\ud83d\udd53", {src: base +"clock4.png"});
      this.register("\ud83d\udd5f", {src: base +"clock430.png"});
      this.register("\ud83d\udd54", {src: base +"clock5.png"});
      this.register("\ud83d\udd60", {src: base +"clock530.png"});
      this.register("\ud83d\udd55", {src: base +"clock6.png"});
      this.register("\ud83d\udd61", {src: base +"clock630.png"});
      this.register("\ud83d\udd56", {src: base +"clock7.png"});
      this.register("\ud83d\udd62", {src: base +"clock730.png"});
      this.register("\ud83d\udd57", {src: base +"clock8.png"});
      this.register("\ud83d\udd63", {src: base +"clock830.png"});
      this.register("\ud83d\udd58", {src: base +"clock9.png"});
      this.register("\ud83d\udd64", {src: base +"clock930.png"});
      this.register("\ud83d\udcd5", {src: base +"closed_book.png"});
      this.register("\ud83d\udd10", {src: base +"closed_lock_with_key.png"});
      this.register("\ud83c\udf02", {src: base +"closed_umbrella.png"});
      this.register("☁", {src: base +"cloud.png"});
      this.register("☁️", {src: base +"cloud.png"});
      this.register("♣", {src: base +"clubs.png"});
      this.register("♣️", {src: base +"clubs.png"});
      this.register("\ud83c\udde8\ud83c\uddf3", {src: base +"cn.png"});
      this.register("\ud83c\udf78", {src: base +"cocktail.png"});
      this.register("☕", {src: base +"coffee.png"});
      this.register("☕️", {src: base +"coffee.png"});
      this.register("\ud83d\ude30", {src: base +"cold_sweat.png"});
      this.register("\ud83d\udca5", {src: base +"collision.png"});
      this.register("\ud83d\udcbb", {src: base +"computer.png"});
      this.register("\ud83c\udf8a", {src: base +"confetti_ball.png"});
      this.register("\ud83d\ude16", {src: base +"confounded.png"});
      this.register("\ud83d\ude15", {src: base +"confused.png"});
      this.register("㊗", {src: base +"congratulations.png"});
      this.register("㊗️", {src: base +"congratulations.png"});
      this.register("\ud83d\udea7", {src: base +"construction.png"});
      this.register("\ud83d\udc77", {src: base +"construction_worker.png"});
      this.register("\ud83c\udfea", {src: base +"convenience_store.png"});
      this.register("\ud83c\udf6a", {src: base +"cookie.png"});
      this.register("\ud83c\udd92", {src: base +"cool.png"});
      this.register("\ud83d\udc6e", {src: base +"cop.png"});
      this.register("\ud83c\udf3d", {src: base +"corn.png"});
      this.register("\ud83d\udc6b", {src: base +"couple.png"});
      this.register("\ud83d\udc91", {src: base +"couple_with_heart.png"});
      this.register("\ud83d\udc8f", {src: base +"couplekiss.png"});
      this.register("\ud83d\udc2e", {src: base +"cow.png"});
      this.register("\ud83d\udc04", {src: base +"cow2.png"});
      this.register("\ud83d\udcb3", {src: base +"credit_card.png"});
      this.register("\ud83c\udf19", {src: base +"crescent_moon.png"});
      this.register("\ud83d\udc0a", {src: base +"crocodile.png"});
      this.register("\ud83c\udf8c", {src: base +"crossed_flags.png"});
      this.register("\ud83d\udc51", {src: base +"crown.png"});
      this.register("\ud83d\ude22", {src: base +"cry.png"});
      this.register("\ud83d\ude3f", {src: base +"crying_cat_face.png"});
      this.register("\ud83d\udd2e", {src: base +"crystal_ball.png"});
      this.register("\ud83d\udc98", {src: base +"cupid.png"});
      this.register("➰", {src: base +"curly_loop.png"});
      this.register("\ud83d\udcb1", {src: base +"currency_exchange.png"});
      this.register("\ud83c\udf5b", {src: base +"curry.png"});
      this.register("\ud83c\udf6e", {src: base +"custard.png"});
      this.register("\ud83d\udec3", {src: base +"customs.png"});
      this.register("\ud83c\udf00", {src: base +"cyclone.png"});
      this.register("\ud83d\udc83", {src: base +"dancer.png"});
      this.register("\ud83d\udc6f", {src: base +"dancers.png"});
      this.register("\ud83c\udf61", {src: base +"dango.png"});
      this.register("\ud83c\udfaf", {src: base +"dart.png"});
      this.register("\ud83d\udca8", {src: base +"dash.png"});
      this.register("\ud83d\udcc5", {src: base +"date.png"});
      this.register("\ud83c\udde9\ud83c\uddea", {src: base +"de.png"});
      this.register("\ud83c\udf33", {src: base +"deciduous_tree.png"});
      this.register("\ud83c\udfec", {src: base +"department_store.png"});
      this.register("\ud83d\udca0", {src: base +"diamond_shape_with_a_dot_inside.png"});
      this.register("♦", {src: base +"diamonds.png"});
      this.register("♦️", {src: base +"diamonds.png"});
      this.register("\ud83d\ude1e", {src: base +"disappointed.png"});
      this.register("\ud83d\ude25", {src: base +"disappointed_relieved.png"});
      this.register("\ud83d\udcab", {src: base +"dizzy.png"});
      this.register("\ud83d\ude35", {src: base +"dizzy_face.png"});
      this.register("\ud83d\udeaf", {src: base +"do_not_litter.png"});
      this.register("\ud83d\udc36", {src: base +"dog.png"});
      this.register("\ud83d\udc15", {src: base +"dog2.png"});
      this.register("\ud83d\udcb5", {src: base +"dollar.png"});
      this.register("\ud83c\udf8e", {src: base +"dolls.png"});
      this.register("\ud83d\udc2c", {src: base +"dolphin.png"});
      this.register("\ud83d\udeaa", {src: base +"door.png"});
      this.register("\ud83c\udf69", {src: base +"doughnut.png"});
      this.register("\ud83d\udc09", {src: base +"dragon.png"});
      this.register("\ud83d\udc32", {src: base +"dragon_face.png"});
      this.register("\ud83d\udc57", {src: base +"dress.png"});
      this.register("\ud83d\udc2a", {src: base +"dromedary_camel.png"});
      this.register("\ud83d\udca7", {src: base +"droplet.png"});
      this.register("\ud83d\udcc0", {src: base +"dvd.png"});
      this.register("\ud83d\udce7", {src: base +"e-mail.png"});
      this.register("\ud83d\udc42", {src: base +"ear.png"});
      this.register("\ud83c\udf3e", {src: base +"ear_of_rice.png"});
      this.register("\ud83c\udf0d", {src: base +"earth_africa.png"});
      this.register("\ud83c\udf0e", {src: base +"earth_americas.png"});
      this.register("\ud83c\udf0f", {src: base +"earth_asia.png"});
      this.register("\ud83c\udf73", {src: base +"egg.png"})
    },
    
    parse(element, options = {}) {
      if (!element) return;

      const walk = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, null, false);
      const nodes = [];

      const size = options.size || "1em"; 

      while (walk.nextNode()) {
        nodes.push(walk.currentNode);
      }

      nodes.forEach((textNode) => {
        const parent = textNode.parentNode;
        const fragments = document.createDocumentFragment();
        let text = textNode.nodeValue;

        Object.keys(emojiMap).forEach((emoji) => {
          const parts = text.split(emoji);
          if (parts.length > 1) {
            for (let i = 0; i < parts.length; i++) {
              fragments.appendChild(document.createTextNode(parts[i]));
              if (i < parts.length - 1) {
                const img = document.createElement('img');
                img.src = emojiMap[emoji];
                img.alt = emoji;
                img.style.width = size;
                img.style.height = size;
                img.style.verticalAlign = "middle";
                fragments.appendChild(img);
              }
            }
            parent.replaceChild(fragments, textNode);
            text = "";
          }
        });
      });
    }
  }
}